services:
    dhammawheel.downloaduserposts.controller.main:
        class: dhammawheel\downloaduserposts\controller\main_controller
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@language'
            - '@user'
            - '@auth'

    dhammawheel.downloaduserposts.listener:
        class: dhammawheel\downloaduserposts\event\main_listener
        arguments:
            - '@language'
            - '@controller.helper'
            - '@template'
            - '@auth'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
