services:
    dhammawheel.blockfoes.listener:
        class: dhammawheel\blockfoes\event\main_listener
        arguments:
            - '@dbal.conn'
            - '@user'
            - '@template'
        tags:
            - { name: event.listener }
