dhammawheel_contactadminposts_contact:
  path: /contact
  defaults:
    _controller: dhammawheel.contactadminposts.controller.contact_controller:handle
    _route: dhammawheel_contactadminposts_contact
