- name: Create temporary directory
  ansible.builtin.tempfile:
    state: directory
    prefix: ffmpeg-static-
  register: ffmpeg_temp_dir
  delegate_to: localhost
  become: false

- name: Download ffmpeg static binaries locally
  ansible.builtin.get_url:
    url: "{{ ffmpeg_static_build_url }}"
    dest: "{{ ffmpeg_temp_dir.path }}/ffmpeg.tar.gz"
    mode: '0644'
  delegate_to: localhost
  run_once: true
  become: false

- name: Extract ffmpeg static binaries
  ansible.builtin.unarchive:
    src: "{{ ffmpeg_temp_dir.path }}/ffmpeg.tar.gz"
    dest: "/usr/local/"
    remote_src: false
    extra_opts:
      - "--strip-components=1"
    exclude:
      - "LICENSE.txt"
    owner: root
    group: root

- name: Set ffmpeg binary permissions
  ansible.builtin.file:
    path: "/usr/local/bin/{{ item }}"
    mode: '0755'
  loop:
    - ffmpeg
    - ffprobe
    - ffplay

- name: Remove local temporary directory
  delegate_to: localhost
  run_once: true
  ansible.builtin.file:
    path: "{{ ffmpeg_temp_dir.path }}"
    state: absent
