- name: Install prerequisites
  ansible.builtin.dnf:
    name:
      - gcc
      - g++
      - libtool
      - autoconf
      - cmake
      - git
    state: present

- name: Download rustup
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: "{{ ansible_env.HOME }}/rustup"
    mode: "a+x"

- name: Install rustc
  ansible.builtin.command:
    cmd: "{{ ansible_env.HOME }}/rustup -y"
    creates: "{{ ansible_env.HOME }}/.cargo/bin/cargo"
  args:
    chdir: "{{ ansible_env.HOME }}"

- name: Add cargo to PATH
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "source $HOME/.cargo/env"
    create: true
    mode: "0644"

- name: Fetch source code
  ansible.builtin.git:
    repo: "{{ spam_filter_repo }}"
    dest: "{{ spam_filter_dir }}"
    version: "{{ spam_filter_version }}"
    depth: 1

- name: Build release binary
  ansible.builtin.command:
    cmd: "{{ ansible_env.HOME }}/.cargo/bin/cargo build --release"
    chdir: "{{ spam_filter_dir }}"
    creates: "{{ spam_filter_dir }}/target/release/rpc"

- name: Copy pretrained model
  ansible.builtin.copy:
    src: model_quantized.onnx
    dest: "{{ spam_filter_model_path }}"
    owner: root
    group: root
    mode: "0644"
