- name: Create spam filter group
  ansible.builtin.group:
    name: "{{ spam_filter_group }}"
    state: present

- name: Create spam filter user
  ansible.builtin.user:
    name: "{{ spam_filter_user }}"
    group: "{{ spam_filter_group }}"
    shell: /sbin/nologin
    system: true
    state: present

- name: Set ownership of spam filter directory
  ansible.builtin.file:
    state: directory
    path: "{{ spam_filter_dir }}"
    owner: "{{ spam_filter_user }}"
    group: "{{ spam_filter_group }}"
    recurse: true

- name: Render systemd service file
  ansible.builtin.template:
    src: spam-filter.service.j2
    dest: /etc/systemd/system/spam-filter.service
    owner: root
    group: root
    mode: "0644"

- name: Start spam-filter service
  ansible.builtin.systemd:
    name: spam-filter
    state: started
    enabled: true
