- name: Mount EFS filesystems
  hosts: dw-mono
  become: true

  vars:
    efs_opts: >-
      nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
    phpbb_efs_mounts:
      - ip: "{{ dhammawheel_efs_ip }}"
        name: com_dhammawheel_www
      - ip: "{{ dharmawheel_efs_ip }}"
        name: net_dharmawheel_www
      - ip: "{{ dharmapaths_efs_ip }}"
        name: com_dharmapaths_www

  tasks:

    - name: Mount /files for phpBB3 sites
      ansible.posix.mount:
        state: mounted
        src: "{{ item.ip }}:/files"
        path: "/var/www/{{ item.name }}/files"
        fstype: nfs4
        opts: "{{ efs_opts }}"
      loop: "{{ phpbb_efs_mounts }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Mount /images for phpBB3 sites
      ansible.posix.mount:
        state: mounted
        src: "{{ item.ip }}:/images"
        path: "/var/www/{{ item.name }}/images"
        fstype: nfs4
        opts: "{{ efs_opts }}"
      loop: "{{ phpbb_efs_mounts }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Mount /images for MediaWiki site
      ansible.posix.mount:
        state: mounted
        src: "{{ dhammawiki_efs_ip }}:/images"
        path: "/var/www/com_dhammawiki_www/images"
        fstype: nfs4
        opts: "{{ efs_opts }}"
