- name: Migrate phpBB3 database
  hosts: dw-mono
  become: true
  vars:
    sites:
      - com_dhammawheel_www
      - net_dharmawheel_www
      - com_dharmapaths_www
  tasks:

    - name: Run migration script
      ansible.builtin.command:
        cmd: |
          php bin/phpbbcli.php db:migrate --safe-mode
        chdir: "/var/www/{{ item }}"
      changed_when: false
      loop: "{{ sites }}"

    - name: Set nginx to owner of cache, files, images, and store directories
      ansible.builtin.command:
        cmd: |
          chown -R nginx:nginx /var/www/{{ item }}/cache
          chown -R nginx:nginx /var/www/{{ item }}/files
          chown -R nginx:nginx /var/www/{{ item }}/images
          chown -R nginx:nginx /var/www/{{ item }}/store
      changed_when: false
      loop: "{{ sites }}"
