- name: Update phpbb3 version
  hosts: localhost
  connection: local

  vars:
    sites:
      - com_dhammawheel_www
      - net_dharmawheel_www
      - com_dharmapaths_www

  tasks:

    - name: Update phpBB3 files for all sites
      ansible.builtin.include_role:
        name: update_phpbb
      vars:
        update_phpbb_site: "{{ item }}"
      loop: "{{ sites }}"
