- name: Verify that the server works
  hosts: dw-mono
  tasks:
    - name: Pause for 10 seconds
      ansible.builtin.pause:
        seconds: 10

    - name: Call health check endpoint
      ansible.builtin.uri:
        url: http://localhost/health
        return_content: true
      register: health_check
      until: health_check.status == 200
      retries: 15
      delay: 5
